name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Match the Node.js version required by your app

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Deploy to Vercelenv:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Add your project ID here
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Add your org ID here if needed
      run: |
        npm install -g vercel
        vercel --prod --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID --confirm --force
